server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: 
    
  main:
    allow-bean-definition-overriding: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



#    spring:
#      main:
#        allow-bean-definition-overriding: true

